### ISSUE TITLE
Multiple encounters in the GET SCR while the POST SCR only have one encounter

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#218]
**Describe the bug**
When Upload SCR with just one encounter, but referenced multiple times, the GET SCR will return multiple encounters 

**To Reproduce**
1. Upload SCR (see attached)
2. GET SCR for the same patient (see attached)
3. See the payload, there are multiple encounters, this may be a symptom of resource and linkage processing in general. 

**Expected behavior**
There should be only one encounter with the attached sample

Upload SCR 
[MultipleEncounter_UploadSCR.txt](https://github.com/NHSDigital/summary-care-record-api/files/6236908/MultipleEncounter_UploadSCR.txt)

GET SCR
[MultipleEncounter_GetSCR.txt](https://github.com/NHSDigital/summary-care-record-api/files/6236910/MultipleEncounter_GetSCR.txt)

**Comment by dawidskainos** [comment]
@Kusnaditjung Encounter resource is used to log participants for Observation/Condition. Due to the way it is stored in XML it is not possible to detect if Observation/Condition have the same Encounter linked. We discussed that with NHS - it is acceptable that the uploaded FHIR structure is slightly different than retrieved one - as long as the information is consistent.
Therefore this issue can be closed.
